# ==========================
# APPLICATION
# ==========================
spring.application.name=portfolio
server.port=8083

# ==========================
# ACTUATOR
# Exposes health and metrics endpoints
# ==========================
management.server.port=9090
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# ==========================
# GRAPHITE METRICS
# Pushes metrics to Graphite every 10 seconds
# ==========================
management.graphite.metrics.export.enabled=true
management.graphite.metrics.export.host=172.19.0.3
management.graphite.metrics.export.port=2003
management.graphite.metrics.export.step=10s
management.graphite.metrics.export.tags-as-prefix=portfolio
management.graphite.metrics.export.protocol=plaintext
# ==========================
# DEVTOOLS
# ==========================
spring.devtools.restart.enabled=true